handleGHRelease: true
manifest: true
releaseType: go

branches:
  - branch: ben_release_please
    releaseType: go
    handleGHRelease: true
    manifest: true
    manifestFile: .release-please-manifest.json
    manifestConfig: release-please-config.json

